### ISSUE TITLE
For .hlf if this files encoded in to UTF-8 required BOM or user can't read text 

### ISSUE THREAD

**Issue by VictorVG** [excelsior-oss/far-git-autocomplete#5]
For .hlf required BOM or user can't read text :)
По русски - для файлов справки надо ставить BOM или система справки Far не опознает UNICODE UTF-8/ На форуме хватает рассуждений на тему "BOM это зло" :) , только все их авторы обязательно упускают из виду что BOM мешающий в их конкретном случае используется не по чьей-то прихоти, а для исключения ошибок детекта кодировок раз, и как флаг того что используется один из вариантов UNICODE два. Понятно, что с ASCII им проще, но UNICODE универсальнее, а если бы им встретилась EBCDIC или ДКОИ-8? Без знания какой это язык правильно прочитать такой текст не удастся, да и то придётся проводить частотный анализ и по нему строить таблицу символов что на малом фрагменте текста невозможно - для выявления частотных закономерностей нужны сотни тысяч символов алфавита, точное знание на каком языке написан данный текст и частотные таблицы языка собственно для воссоздания использованной кодовой таблицы .

Сейчас имеем:

Оригинал без (Original, w/o BOM) в (in) GitAutocomplete_ru.hlf:

![wo_bom](https://cloud.githubusercontent.com/assets/906886/20925155/3779e6e4-bbc6-11e6-9d02-090d018c08e8.png)

Добавим BOM (Added BOM) в (in) GitAutocomplete_ru.hlf:

![bom_inserted](https://cloud.githubusercontent.com/assets/906886/20925186/68e9ed6e-bbc6-11e6-9c51-1496d5613e5c.png)

**Comment by cypok** [comment]
Интереса ради, у вас какой-то особый Far? Ибо моя текущая версия нормально открывает справку:
![far-ru-help-ok](https://cloud.githubusercontent.com/assets/16010/20959805/807b0d18-bc8f-11e6-8b16-ff6fbe3d7d45.PNG)
Хочется иметь возможность воспроизвести проблему.

**Comment by VictorVG** [comment]
Да, нет простая сборка, всегда лежит тут если что в [**./Far3**](https://yadi.sk/d/oc1fPSIbhvvwT0) , хотя линки там более-менее постоянные. Far30latest-x86_x64-bin.7z этот архив содержит только х86 и AMD64 ,бинарники, часто без NetBox и Colorer - собираю из SVN, а остальное - Far30-x64-test.7z тут х64 сборка которой сам и пользуюсь, FarUE3.7z её х86 вариант, только в NSIS завёрнутый,  farue3-update.7z - пакет обновления для х86 редакции....

**Comment by VictorVG** [comment]
Да, судя по комментариям в обсуждении есть повод и пересобрать плагин (тут я бы воспользовался или VC2010, или GCC поскольку уже приходилось встречать случаи когда и vc1х0_xp тулкит, и записи в мэйке или солюшене указывавшие на необходимость собрать бинарник для ХР студия игнорирует и в импортах находишь вызовы для виста и более старших систем, и сразу ВОМ вставить чтобы исключить "всплытие" этой уже устранённой нами ошибки в принципе - лучше перестраховаться, чем после удивляться. :)

**Comment by cypok** [comment]
> сразу ВОМ вставить

Поясните? Его надо вставить еще где-то кроме `.hlf` и `.lng` файлов?

**Comment by VictorVG** [comment]
Нет. Только в них, остальные файлы если что по ShiftF8 пусть читают. Иначе зачем переключатель в Far встроен?:)
